# Physical Geodesy lab 2

In [1]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import eigs

y=np.array([[3854.692 ,3854.692 ,3854.691] , [3852.795, 3852.794, 3852.793], [3854.671, 3854.671, 3854.673], [3852.769, 3852.771, 3852.775], [3849.806, 3849.811, 3849.815],[3852.789, 3852.790, 3852.787], [3849.823, 3849.823, 3849.820]])

print(y)

[[3854.692 3854.692 3854.691]
 [3852.795 3852.794 3852.793]
 [3854.671 3854.671 3854.673]
 [3852.769 3852.771 3852.775]
 [3849.806 3849.811 3849.815]
 [3852.789 3852.79  3852.787]
 [3849.823 3849.823 3849.82 ]]


In [2]:
y3=y.mean(axis=1)[:, np.newaxis]
print(y3)

[[3854.69166667]
 [3852.794     ]
 [3854.67166667]
 [3852.77166667]
 [3849.81066667]
 [3852.78866667]
 [3849.822     ]]


In [3]:
d=y-np.c_[y3,y3,y3]
print(d)

[[ 0.00033333  0.00033333 -0.00066667]
 [ 0.001       0.         -0.001     ]
 [-0.00066667 -0.00066667  0.00133333]
 [-0.00266667 -0.00066667  0.00333333]
 [-0.00466667  0.00033333  0.00433333]
 [ 0.00033333  0.00133333 -0.00166667]
 [ 0.001       0.001      -0.002     ]]


In [4]:
dd=d**2
s=np.sqrt(sum(dd.T)/6)
print(s)
s_l=s/np.sqrt(7)
print(s_l)

[0.00033333 0.00057735 0.00066667 0.00176383 0.00260342 0.00088192
 0.001     ]
[0.00012599 0.00021822 0.00025198 0.00066667 0.000984   0.00033333
 0.00037796]


In [5]:
delta_y=y3-y3[1]
print(delta_y)
delta_y=np.vstack((delta_y[0],delta_y[2:7]))
print(delta_y)

[[ 1.89766667]
 [ 0.        ]
 [ 1.87766667]
 [-0.02233333]
 [-2.98333333]
 [-0.00533333]
 [-2.972     ]]
[[ 1.89766667]
 [ 1.87766667]
 [-0.02233333]
 [-2.98333333]
 [-0.00533333]
 [-2.972     ]]


In [6]:
t=np.array([[44473.44546,44473.44618,44473.44689],[44473.45494,44473.45567,44473.45638],[44473.46275,44473.46348,44473.46419],[44473.47038,44473.47111,44473.47181],[44473.47719,44473.47791,44473.47862],[44473.48299,44473.48372,44473.48442],[44473.48984,44473.49057,44473.49127]])
print(t)

[[44473.44546 44473.44618 44473.44689]
 [44473.45494 44473.45567 44473.45638]
 [44473.46275 44473.46348 44473.46419]
 [44473.47038 44473.47111 44473.47181]
 [44473.47719 44473.47791 44473.47862]
 [44473.48299 44473.48372 44473.48442]
 [44473.48984 44473.49057 44473.49127]]
