# Physikalische Geodäsie Übung 2

In [1]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import eigs

y=np.array([[3854.692 ,3854.692 ,3854.691] , [3852.795, 3852.794, 3852.793], [3854.671, 3854.671, 3854.673], [3852.769, 3852.771, 3852.775], [3849.806, 3849.811, 3849.815],[3852.789, 3852.790, 3852.787], [3849.823, 3849.823, 3849.820]])

print(y)

[[3854.692 3854.692 3854.691]
 [3852.795 3852.794 3852.793]
 [3854.671 3854.671 3854.673]
 [3852.769 3852.771 3852.775]
 [3849.806 3849.811 3849.815]
 [3852.789 3852.79  3852.787]
 [3849.823 3849.823 3849.82 ]]


In [2]:
y3=y.mean(axis=1)
print(y3)

[3854.69166667 3852.794      3854.67166667 3852.77166667 3849.81066667
 3852.78866667 3849.822     ]


In [3]:
d=np.zeros(y.shape)
for i in range(0,7):
    d[i,:]=y[i,:]-y3[i]
print(d)

[[ 0.00033333  0.00033333 -0.00066667]
 [ 0.001       0.         -0.001     ]
 [-0.00066667 -0.00066667  0.00133333]
 [-0.00266667 -0.00066667  0.00333333]
 [-0.00466667  0.00033333  0.00433333]
 [ 0.00033333  0.00133333 -0.00166667]
 [ 0.001       0.001      -0.002     ]]


In [4]:
dd=d**2
s=np.sqrt(sum(dd.T)/6)
print(s)

[0.00033333 0.00057735 0.00066667 0.00176383 0.00260342 0.00088192
 0.001     ]
